### ISSUE TITLE
Enchancement: Remove hud in gamemodes other than survival

### ISSUE THREAD

**Issue by justlukie** [Sea-Kerman/InventoryFullAlert#7]
There isn't really any reason for the hud to be displayed when in spectator or creative and I think it would make sense if it automatically went away when you enter a gamemode other than survival

**Comment by Sea-Kerman** [comment]
I get your point about spectator mode but it's important for creative mode because if your inventory's full there, it's even worse because you pick up the items anyway and they get deleted.

**Comment by Sea-Kerman** [comment]
I've added the ability to turn the hud off in the config in the new release
